// Stub components - booking insights removed
export const BookingKPICards = () => null;
export const BookingStatusLineChart = () => null;
export const LeastBookedTeamMembersTable = () => null;
export const MostBookedTeamMembersTable = () => null;
export const TotalBookingUsersTable = () => null;
export const AverageEventDurationChart = () => null;
export const PopularEventsTable = () => null;
export const HighestNoShowHostTable = () => null;
export const RecentFeedbackTable = () => null;
export const HighestRatedMembersTable = () => null;
export const LowestRatedMembersTable = () => null;
